# manual (marker for update script to not modify this file)
language: python
python:
    - 2.6
    - 2.7
    - 3.3
install:
    - pip install ZODB-4.0.0dev.tar.gz --use-mirrors
    - pip install . --use-mirrors
script:
    - python setup.py test -q
notifications:
    email: false
